name: Release

on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_BUILDKIT: 0
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Fetch latest tag"
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Build and push Postgres 17
        id: docker_build_17
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PG_VERSION=17.0
            PG_MAJOR_VERSION=17
            VERSION=${{ steps.get-latest-tag.outputs.tag }}
          context: .
          file: ./Dockerfile
          push: true
          labels: |
            org.opencontainers.image.source="https://github.com/GRoguelon/postgres-flex"
          tags: |
            ghcr.io/groguelon/postgres-flex:17
            ghcr.io/groguelon/postgres-flex:17.0
      - name: Build and push Postgres 17 Timescale DB
        id: docker_build_17_timescaledb
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PG_VERSION=17.0
            PG_MAJOR_VERSION=17
            VERSION=${{ steps.get-latest-tag.outputs.tag }}
          context: .
          file: ./Dockerfile-timescaledb
          push: true
          labels: |
            org.opencontainers.image.source="https://github.com/GRoguelon/postgres-flex"
          tags: |
            ghcr.io/groguelon/postgres-flex-timescaledb:17
            ghcr.io/groguelon/postgres-flex-timescaledb:17.0
      - name: Postgres 17 Image digest
        run: echo ${{ steps.docker_build_17.outputs.digest }}
      - name: Postgres 17 TimescaleDB Image digest
        run: echo ${{ steps.docker_build_17_timescaledb.outputs.digest }}
